const schemaTaxAssessor = {
  taxAssessor: (value, limit = 1) => `
    query MyQuery {
      tax_assessor(where: {tax_assessor_id: {_eq: "${value}"}}, limit: ${limit}) {
        account_number
        address
        alternate_assessor_parcel_number
        assessed_improvements_percent
        assessed_tax_year
        assessed_value_improvements
        assessed_value_land
        assessed_value_total
        assessor_parcel_number_formatted
        assessor_parcel_number_raw
        assessor_parcel_number_year_change
        attic_sq_ft
        balcony_sq_ft
        basement_finished_sq_ft
        basement_sq_ft
        basement_unfinished_sq_ft
        bath_count
        bath_house_sq_ft
        bed_count
        boat_house_sq_ft
        building_sq_ft
        building_sq_ft_code
        building_storage_sq_ft
        building_utility_sq_ft
        buildings_count
        cabin_sq_ft
        canopy_sq_ft
        cbsa
        cbsa_code
        cbsa_name
        census_block
        census_block_group
        census_fips_code
        census_tract
        cherre_deleted_at
        cherre_is_deleted
        cherre_lot_size_acre_calculated
        cherre_lot_size_sq_ft_calculated
        cherre_parcel_id
        cherre_updated_at
        city
        congressional_district
        construction_code
        courtyard_sq_ft
        crrt
        data_publish_date
        deck_sq_ft
        deed_last_sale_document_book
        deed_last_sale_document_number
        deed_last_sale_document_page
        deed_last_sale_price
        description
        driveway_material_code
        driveway_sq_ft
        effective_year_built
        exterior_code
        fence_code
        fence_sq_ft
        fips_code
        fire_resistance_class_code
        fireplace_code
        fireplace_count
        fiscal_year
        floor_1_sq_ft
        floor_2_sq_ft
        flooring_material_code
        foundation_code
        gazebo_sq_ft
        geocode_quality_code
        grainery_sq_ft
        green_house_sq_ft
        gross_sq_ft
        guest_house_sq_ft
        has_alarm_system
        has_arbor_pergola
        has_attic
        has_balcony
        has_bath_house
        has_boat_access
        has_boat_house
        has_boat_lift
        has_bonus_room
        has_breakfast_nook
        has_breezeway
        has_building_storage
        has_building_utility
        has_cabin
        has_canopy
        has_cellar
        has_central_vacuum_system
        has_community_rec_room
        has_courtyard
        has_deck
        has_elevator
        has_equestrian_arena
        has_escalator
        has_exercise_room
        has_family_room
        has_fire_sprinkers
        has_game_room
        has_gazebo
        has_golf_course_green
        has_grainery
        has_great_room
        has_green_house
        has_guest_house
        has_hobby_room
        has_home_office
        has_installed_sound_system
        has_intercom
        has_kennel
        has_laundry_room
        has_lean_to
        has_loading_platform
        has_media_room
        has_milk_house
        has_mobile_home_hookup
        has_mud_room
        has_other_sport_court
        has_outdoor_kitchen_fireplace
        has_overhead_door
        has_parking_carport
        has_pole_structure
        has_pond
        has_pool_house
        has_poultry_house
        has_quonset
        has_rv_parking
        has_safe_room
        has_sauna
        has_shed
        has_silo
        has_sitting_room
        has_sprinklers
        has_stable
        has_storm_shelter
        has_storm_shutter
        has_study
        has_sunroom
        has_tennis_court
        has_utility_room
        has_water_feature
        has_wet_bar
        has_wine_cellar
        home_office_sq_ft
        house_number
        hvacc_cooling_code
        hvacc_heating_code
        hvacc_heating_fuel_code
        interior_structure_code
        is_additional_exemption
        is_address_info_private
        is_disabled_exemption
        is_from_deed_record
        is_handicap_accessible
        is_homeowner_exemption
        is_mailing_info_private
        is_owner_occupied
        is_senior_exemption
        is_veteran_exemption
        is_widow_exemption
        jurisdiction
        kennel_sq_ft
        last_deed_sale_date
        last_ownership_change_date
        last_ownership_transfer_document_number
        last_sale_amount
        latitude
        lean_to_sq_ft
        legal_unit_number
        loading_platform_sq_ft
        longitude
        lot_depth_ft
        lot_size_acre
        lot_size_sq_ft
        lot_width
        mailing_address
        mailing_city
        mailing_county
        mailing_crrt
        mailing_fips_code
        mailing_format_code
        mailing_house_number
        mailing_state
        mailing_street_direction
        mailing_street_name
        mailing_street_post_direction
        mailing_street_suffix
        mailing_unit_number
        mailing_unit_prefix
        mailing_zip
        mailing_zip_4
        map_book
        map_page
        market_improvements_percent
        market_value_improvements
        market_value_total
        market_value_year
        metro_division
        milk_house_sq_ft
        minor_civil_division_code
        minor_civil_division_name
        msa_code
        msa_name
        neighborhood_code
        one_line_address
        one_line_address_mailing
        parcel_number_year_added
        parking_carport_sq_ft
        parking_garage_code
        parking_space_count
        parking_sq_ft
        partial_bath_count
        patio_sq_ft
        phase
        plumbing_feature_count
        pole_structure_sq_ft
        pool_code
        pool_house_sq_ft
        pool_sq_ft
        porch_code
        porch_sq_ft
        poultry_house_sq_ft
        previous_assessed_value
        previous_assessor_parcel_number
        prior_sale_amount
        property_group_type
        property_municipal_use
        property_use_code_mapped
        property_use_standardized_code
        quarter
        quarter_quarter
        quonset_sq_ft
        range
        roof_construction_code
        roof_material_code
        room_count
        section
        sewer_usage_code
        shed_sq_ft
        silo_sq_ft
        situs_county
        situs_state
        stable_sq_ft
        state
        stories_count
        street_direction
        street_name
        street_post_direction
        street_suffix
        structure_style_code
        subdivision
        tax_assessor_id
        tax_assessor_last_sale_date
        tax_assessor_last_update_date
        tax_assessor_prior_sale_date
        tax_bill_amount
        tax_delinquent_year
        tax_district_code
        tax_roll_update_date
        the_value_land
        topography_code
        township
        tract
        unit_number
        unit_prefix
        units_count
        upper_floor_sq_ft
        utility_sq_ft
        view_code
        water_source_code
        year_built
        zip
        zip_4
        zone_code
      }
    }
  `,
  taxAssessorBlock: (value, limit = 1) =>`
    query MyQuery {
      tax_assessor_block(where: {tax_assessor_id: {_eq: "${value}"}}, limit: ${limit}) {
        block
        cherre_tax_assessor_block_pk
        tax_assessor_id
      }
    }
  `,
  taxAssessorLot: (value, limit = 1) =>`
    query MyQuery {
      tax_assessor_lot(where: {tax_assessor_id: {_eq: "${value}"}}, limit: ${limit}) {
        cherre_tax_assessor_lot_pk
        lot
        tax_assessor_id
      }
    }
  `,
  taxAssessorOwner: (value, limit = 1) =>`
    query MyQuery {
      tax_assessor_owner(where: {tax_assessor_id: {_eq: "${value}"}}, limit: ${limit}) {
        cherre_tax_assessor_owner_pk
        is_owner_company
        owner_first_name
        owner_first_name_latest_deed
        owner_last_name
        owner_last_name_latest_deed
        owner_middle_name
        owner_middle_name_latest_deed
        owner_name
        owner_name_latest_deed
        owner_name_suffix
        owner_name_suffix_latest_deed
        owner_trust_type_code
        owner_type
        ownership_vesting_relation_code
        tax_assessor_id
      }
    }
  `
}
export default schemaTaxAssessor;